version: '3.1'
services:
  copper:
    image: "klumw/copper-full:prom-5.2020.7-jdk11"
    environment:
      - "POSTGRES_PASSWORD=${DB_PWD}"
      - "POSTGRES_USER=${DB_USER}"
    ports:
      - 8080:8080
      - 8083:8083
    depends_on:
      - postgres
      - mock
  postgres:
    image: "postgres:12.5-alpine"
    environment:
      - "POSTGRES_PASSWORD=${DB_PWD}"
      - "POSTGRES_USER=${DB_USER}"
    ports:
      - 5432:5432
  monitoring:
    image: "copperengine/copper-monitoring"
    ports:
      - 8081:8080
    environment:
      - JMX_HOST=copper
      - JMX_PORT=1099
    depends_on:
      - copper
  mock:
    image: "klumw/copper-mock:5.2020.7-jdk11"
    ports:
      - 8082:8080
  prometheus:
    image: "prom/prometheus:v2.15.2"
    ports:
      - 9090:9090
    volumes:
      - ./resources/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - copper
  grafana:
     image: "grafana/grafana:6.5.3"
     ports:
      - 3000:3000
     depends_on:
       - prometheus



