version: '3.1'
services:
  copper:
    image: "klumw/copper-full:latest"
    entrypoint:
      - java
      - -XX:+UseContainerSupport
      - -XX:MaxRAMPercentage=90.0
      - -Dcom.sun.management.jmxremote.port=1099
      - -Dcom.sun.management.jmxremote.rmi.port=1099
      - -Dcom.sun.management.jmxremote.authenticate=false
      - -Dcom.sun.management.jmxremote.ssl=false
      - -jar
      - payara-micro.jar
      - --deploymentDir
      - /opt/payara/deployments
      - --nocluster
    ports:
      - 8080:8080
      - 1099:1099
    depends_on:
      - postgres
      - mock
  postgres:
    image: "postgres:9.6.16-alpine"
    ports:
      - 5432:5432
  monitoring:
    image: "copperengine/copper-monitoring"
    ports:
      - 8081:8080
    environment:
      - JMX_HOST=copper
      - JMX_PORT=1099
    depends_on:
      - copper
  mock:
    image: "klumw/copper-mock"
    ports:
      - 8082:8080
  telegraf:
    image: "telegraf:1.11-alpine"
    command: bash -c "/wait-for-it.sh -t 0 influxdb:8086 && telegraf"
    volumes:
      - "./telegraf.conf:/etc/telegraf/telegraf.conf:ro"
      - "./wait-for-it.sh:/wait-for-it.sh"
    depends_on:
      - "influxdb"
  influxdb:
    image: "influxdb:1.7.9"
    ports:
      - 8086:8086
  chronograf:
    image: "chronograf:1.7.16-alpine"
    command: "chronograf --influxdb-url=http://influxdb:8086"
    ports:
      - 8888:8888
    depends_on:
      - "influxdb"


