version: '3.1'
services:
  copper:
    image: "payara/micro:jdk11"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    entrypoint:
      - java
      - -XX:+UseContainerSupport
      - -XX:MaxRAMPercentage=90.0
      - -Dorg.copperengine.asm.api.version=7
      - -jar
      - payara-micro.jar
      - --deploymentDir
      - /opt/payara/deployments
      - --nocluster
    volumes:
      - "./target:/opt/payara/deployments"
    ports:
      - 8080:8080
    depends_on:
      - postgres
  postgres:
    image: "postgres:12.2-alpine"
    environment:
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_USER=postgres
    ports:
      - 5432:5432
