version: '3.1'
services:
  copper:
    build: .
    image: "copper-starter:latest"
    ports:
      - 8080:8080
  postgres:
    image: "postgres:12.5-alpine"
    environment:
      - "POSTGRES_PASSWORD=${DB_PWD}"
      - "POSTGRES_USER=${DB_USER}"
    ports:
      - 5432:5432
