---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
  namespace: default
  labels:
    app: postgres-db
spec:
  containers:
    - name: postgres-db
      image: postgres:9.6.16-alpine
      ports:
        - name: db-port
          containerPort: 5432
---
apiVersion: v1
kind: Pod
metadata:
  name: copper-full
  namespace: default
  labels:
    app: copper-full
spec:
  containers:
    - name: copper-full
      image: klumw/copper-full
      command: ["java"]
      args: ["-XX:+UseContainerSupport","-XX:MaxRAMPercentage=90.0","-Dcom.sun.management.jmxremote.port=1099","-Dcom.sun.management.jmxremote.rmi.port=1099","-Dcom.sun.management.jmxremote.authenticate=false","-Dcom.sun.management.jmxremote.ssl=false","-jar","payara-micro.jar","--deploymentDir","/opt/payara/deployments","--nocluster"]
      ports:
        - name: copper-input
          containerPort: 8080
        - name: jmx-port
          containerPort: 1099
          hostPort: 1099
---
apiVersion: v1
kind: Pod
metadata:
  name: copper-mock
  namespace: default
  labels:
    app: copper-mock
spec:
  containers:
    - name: mock-server
      image: klumw/copper-mock
      ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: copper-monitoring
  namespace: default
  labels:
    app: copper-monitoring
spec:
  containers:
    - name: copper-monitoring
      image: copperengine/copper-monitoring
      env:
        - name: JMX_HOST
          value: "copper"
        - name: JMX_PORT
          value: "1099"
      ports:
        - name: http-mon
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mock
spec:
  selector:
    app: copper-mock
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: db-port
---
apiVersion: v1
kind: Service
metadata:
  name: copper
spec:
  selector:
    app: copper-full
  ports:
    - protocol: TCP
      port: 1099
      targetPort: jmx-port
