---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
  namespace: default
  labels:
    app: postgres-db
spec:
  containers:
    - name: postgres-db
      image: postgres:12.2-alpine
      env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
      ports:
        - name: db-port
          containerPort: 5432
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: copper-full
  labels:
    app: copper-full
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: middletier
  template:
    metadata:
      labels:
        tier: middletier
    spec:    
      containers:
      - name: copper-full
        image: klumw/copper-full:5.201-jdk11
        env:
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_USER
            value: "postgres"
        ports:
        - name: copper-input
          containerPort: 8080
        - name: jmx-port
          containerPort: 1099
---
apiVersion: v1
kind: Pod
metadata:
  name: copper-mock
  namespace: default
  labels:
    app: copper-mock
spec:
  containers:
    - name: mock-server
      image: klumw/copper-mock
      ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: copper-monitoring
  namespace: default
  labels:
    app: copper-monitoring
spec:
  containers:
    - name: copper-monitoring
      image: copperengine/copper-monitoring
      env:
        - name: JMX_HOST
          value: "copper"
        - name: JMX_PORT
          value: "1099"
      ports:
        - name: http-mon
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mock
spec:
  selector:
    app: copper-mock
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: db-port
---
apiVersion: v1
kind: Service
metadata:
  name: copper
spec:
  selector:
    tier: middletier
  ports:
    - name: jmx
      protocol: TCP
      port: 1099
      targetPort: jmx-port
    - name: http
      protocol: TCP
      port: 8080
      targetPort: copper-input
---
