apiVersion: v1
kind: Service
metadata:
  name: mock
spec:
  selector:
    app: copper-mock
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: db-port
---
apiVersion: v1
kind: Service
metadata:
  name: copper
spec:
  selector:
    app: copper-engine
  type: NodePort
  ports:
    - name: jmx
      protocol: TCP
      port: 1099
      targetPort: jmx-port
    - name: http
      protocol: TCP
      port: 8080
      targetPort: copper-input
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db
spec:
  selector:
    matchLabels:
      app: postgres-db
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-db
        tier: backend
    spec:
      containers:
        - name: postgres-12
          image: postgres:12.5-alpine
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
          ports:
            - name: db-port
              containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copper-full
spec:
  selector:
    matchLabels:
      app: copper-engine
  replicas: 1
  template:
    metadata:
      labels:
        app: copper-engine
        tier: middletier
    spec:
      containers:
        - name: copper-full
          image: klumw/copper-full:5.2020.7-jdk11
          env:
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_USER
              value: "postgres"
          ports:
            - name: copper-input
              containerPort: 8080
            - name: jmx-port
              containerPort: 1099
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copper-mock
spec:
  selector:
    matchLabels:
      app: copper-mock
  replicas: 1
  template:
    metadata:
      labels:
        app: copper-mock
        tier: backend
    spec:
      containers:
        - name: mock-server
          image: klumw/copper-mock:5.2020.7-jdk11
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: copper-monitoring
spec:
  selector:
    matchLabels:
      app: copper-monitoring
  replicas: 1
  template:
    metadata:
      labels:
        app: copper-monitoring
        tier: frontend
    spec:
      containers:
        - name: copper-gui
          image: copperengine/copper-monitoring
          resources:
            requests:
              memory: "600Mi"
              cpu: "250m"
            limits:
              memory: "700Mi"
              cpu: "500m"
          env:
            - name: JMX_HOST
              value: "copper"
            - name: JMX_PORT
              value: "1099"
          ports:
            - name: http-mon
              containerPort: 8080
---

