version: '3.1'
services:
  copper:
    image: "payara/micro:jdk11"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    entrypoint:
      - java
      - -XX:+UseContainerSupport
      - -XX:MaxRAMPercentage=90.0
      - -Dcom.sun.management.jmxremote.port=1099
      - -Dcom.sun.management.jmxremote.rmi.port=1099
      - -Dcom.sun.management.jmxremote.authenticate=false
      - -Dcom.sun.management.jmxremote.ssl=false
      - -Dorg.copperengine.asm.api.version=7
      - -jar
      - payara-micro.jar
      - --deploymentDir
      - /opt/payara/deployments
      - --nocluster
    volumes:
      - "./target:/opt/payara/deployments"
    ports:
      - 8080:8080
      - 1099:1099
    depends_on:
      - postgres
  postgres:
    image: "postgres:12.2-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
  monitoring:
    image: "copperengine/copper-monitoring"
    ports:
      - 8081:8080
    environment:
      - JMX_HOST=copper
      - JMX_PORT=1099
    depends_on:
      - copper
  mock:
    image: "klumw/copper-mock"
    ports:
      - 8082:8080


