version: '3.1'
services:
  copper:
    build: .
    image: copper-full:latest
    ports:
      - "8080:8080"
  postgres:
    image: "postgres:12.2-alpine"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
